credit_card_dwh:
  outputs:
    dev:
      dataset: test_location
      fixed_retries: 1
      keyfile: /opt/airflow/cred/google_credentials.json
      location: us
      method: service-account
      priority: interactive
      project: "forward-entity-411314"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: test_location
      fixed_retries: 1
      keyfile: /opt/airflow/cred/google_credentials.json
      location: us
      method: service-account
      priority: interactive
      project: "forward-entity-411314"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
